#!/bin/bash

name=$(jq -r '.name' data.json | sed 's/\b\(.\)/\U\1/g')
height=$(jq -r '.height' data.json)
weight=$(jq -r '.weight' data.json)
type=$(jq -r '.type' data.json | sed 's/\b\(.\)/\U\1/g')

formatted_height=$(awk "BEGIN {printf \"%.2f\", $height/10}")
formatted_weight=$(awk "BEGIN {printf \"%.2f\", $weight/10}")

echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."
